WDP210701-22
odevpl/wdp-2107-01 pull request #32
Opened 2021-07-21 17:51 UTC by B7atis

Please check my code.

2021-07-21 19:05 UTC, Myszczyson requested changes
1. Korzystasz z Base Colours zamiast Component Colours (zadanie WDP210701-8)
2. Przyciski w PromotedBox2 nie są rozciągnięte do końca 
3. Div z ceną produktu ma dwa dolary dla oldPrice .
4. oldPrice znajduję się w tym samym divie, a na zdjęciu design pokazywał go poza divem z lewej strony w kolorze białym

2021-07-22 17:53 UTC, B7atis commented
Wprowadziłem poprawki, sprawdź proszę.

2021-07-22 18:37 UTC, Myszczyson requested changes
Jeszcze kolory zostały, cała reszta zrobiona 👍

2021-07-22 18:37 UTC, Myszczyson commented on src/components/common/Promoted/PromotedBox.module.scss
> +  background-color: $white;
Dalej korzystasz z  Base Colours 

![image](https://user-images.githubusercontent.com/78232313/126691149-a7dd06a9-b26c-4e31-aa9f-ce5b418e8010.png)

2021-07-22 18:37 UTC, Myszczyson commented on src/components/common/Promoted/PromotedBox.module.scss
> +// @import "../Button/Button.module.scss";
Niepotrzebne to usuwamy (flashback)

2021-07-22 20:02 UTC, B7atis commented
Zrobione.

2021-07-22 21:17 UTC, Myszczyson approved these changes

2021-07-23 08:02 UTC, merged