Wdp210701 21
odevpl/wdp-2107-01 pull request #38
Opened 2021-07-23 20:27 UTC by AniaSzwal

PROBLEM: Trzeba było dodać inny tryb działania gwiazdek. Powinny być złote (tzn. w tym samym kolorze co np. hover guzików), i one oznaczają "moja ocena".

SOLUTION: Wydzielony został osobny komponent na gwiazdki i zmodyfikowany component productBox. Gdy produkt nie ma 'mojej oceny', to ma średnią (czarne gwiazdki), a jak ma moją ocenę to widać moją (zlote gwiazdki). Klient rozumie, że w takim razie jak ktoś wybierze swoją ocenę, to nie będzie widział średniej oceny (tej początkowej, na czarno) i to jest ok. Na hover gwiazdki też są złote. Jak się najedzie np. na 1. gwiazdkę to tylko 1 ma być wypełniona (pozostałe puste), a jak się najedzie np. na 4. gwiazdkę, to mają być 4 wypełnione (i 1 pusta). Po kliknięciu w gwiazdkę zapisuje się moja ocena w stanie aplikacji, czyli np. kliknięta 4. gwiazdka, to 4 gwiazdki mają być wypełnione i 1 pusta. Po odświeżeniu strony klient widzi od razu "moją ocenę" w co najmniej jednym produkcie (przykładowe dane zostaly wrzucone do stanu początkowego-initialState)

2021-07-23 21:43 UTC, AniaSzwal commented
moze ktos mi sprawdzic czy nie mam konfliktów? Bo mi zwariowało IDE i teraz juz sama nie wiem.

2021-07-25 10:57 UTC, AniaSzwal commented
Konflikty rozwiązane, proszę o review

2021-07-25 12:02 UTC, Myszczyson requested changes
Po odpaleniu z brancha wywala błędy typu brak domknięcia buttona albo diva.  Odpal se brancha na kompie, jeżeli pokazuje 
![image](https://user-images.githubusercontent.com/78232313/126898229-4be60dd7-af72-45dc-8c26-9d1af8c4bd84.png)
zrób git pull, żeby sciągnąć poprawki z konfliktami i trzeba poprawić te errory które wyskakują po kolei

2021-07-26 20:50 UTC, agiskorska approved these changes
Zaznacza i odznacza elegancko :)

2021-07-27 20:22 UTC, B7atis approved these changes

2021-07-28 07:44 UTC, odevpl approved these changes

2021-07-28 07:44 UTC, merged