Task 31
odevpl/wdp-2107-01 pull request #39
Opened 2021-07-25 20:54 UTC by agiskorska

2021-07-26 18:07 UTC, Myszczyson requested changes

2021-07-26 18:07 UTC, Myszczyson commented on src/components/layout/Brands/Brands.js
> +  // displayBrands(brands, picNubmer) {
Niepotrzebne to usuń, reszta śmiga :)

2021-07-26 18:45 UTC, Myszczyson approved these changes

2021-07-26 20:24 UTC, AniaSzwal approved these changes

2021-07-27 20:49 UTC, odevpl requested changes
Popraw proszę konflikty

2021-07-28 08:00 UTC, odevpl approved these changes

2021-07-28 08:00 UTC, merged