Add functionality to gallery component
odevpl/wdp-2107-01 pull request #40
Opened 2021-07-26 17:24 UTC by AniaSzwal

Zrobiłam połowę taska, zaimplementowałam funkcjonalność: Kiedy aktywna jest np. kategoria "Top Seller", a kliknie się "Featured", to ma zniknąć (z animacją fade) cały slider pod tabami (główne zdjęcie i slider z miniaturkami poniżej), po czym ma się pojawić slider z innymi elementami (też z animacją fade). Każdy tab ma mieć własny, osobny zestaw elementów. Jest problem ze zdjęciami, nie wiem, czemu stylowanie nie łapie. Mozecie sprawdzić u siebie?

2021-07-26 18:51 UTC, agiskorska requested changes

2021-07-26 18:51 UTC, agiskorska commented on src/components/features/Gallery/Gallery.js
> +                        <img alt={activeProduct.name} src={activeProduct.image} />
Tutaj mozesz wstawic <img .... width='500px' ... /> i wszystko gra

2021-07-26 19:31 UTC, agiskorska reviewed
No i super!

2021-07-26 19:31 UTC, agiskorska approved these changes

2021-07-27 20:21 UTC, B7atis approved these changes
Popraw tylko konflikty.

2021-07-28 08:02 UTC, merged